### ISSUE TITLE
报错，详细情况见下文

### ISSUE THREAD

**Issue by Fiend1019** [renmu123/bilibili-manga-downloader#1]
C:\Users\Mr.wu\Desktop\1>bili-comic-download.exe bili-comic-download 27923
选择下载模式:
 [0] ep
 [1] ord
 > ep
请输入需要下载的漫画章节，支持用“,”分隔：
 438701
[INFO] 领主什么的无所谓啦
[INFO] 第 2 话开始下载

  OSError

  [WinError 123] 文件名、目录名或卷标语法不正确。: 'downloads\\领主什么的无所谓啦\\2第二话\t'

  at pathlib.py:1194 in stat

**Comment by renmu123** [comment]
明白了，应该win文件命名限制问题，我晚上修复一下

**Comment by Fiend1019** [comment]
> 明白了，应该win文件命名限制问题，我晚上修复一下

好的，麻烦了
